services:
  server:
    build: .
    # ports:
    #   - "2222:2222"
    network_mode: "host"
    env_file:
      - .env
    environment:
      - MCP_BASE_URL=${MCP_BASE_URL}
    restart: unless-stopped
